[package]
name = "katselin-actix-android"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "libactix"
path = "src/main.rs"

[dependencies]
actix-web = { version = "4", default-features = false, features = ["macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[workspace]
